const approvalConfig={paymentUrl:''}; // Add the payment/invoice URL or later replace with a per-order secure payment flow.
const order=document.getElementById('approvalOrder'),nameField=document.getElementById('approvalName'),version=document.getElementById('approvalVersion'),amount=document.getElementById('approvalAmount'),signature=document.getElementById('signatureName');
const checks=[...document.querySelectorAll('.approval-check')],signBtn=document.getElementById('signAccept'),status=document.getElementById('approvalStatus'),paymentGate=document.getElementById('paymentGate'),receipt=document.getElementById('agreementReceipt');
function validate(){const same=signature.value.trim().toLowerCase()===nameField.value.trim().toLowerCase();signBtn.disabled=!(order.value.trim()&&nameField.value.trim()&&version.value.trim()&&amount.value.trim()&&same&&checks.every(c=>c.checked));}
[order,nameField,version,amount,signature,...checks].forEach(el=>el.addEventListener('input',validate));checks.forEach(el=>el.addEventListener('change',validate));
document.getElementById('proofUpload').addEventListener('change',e=>{const f=e.target.files&&e.target.files[0],img=document.getElementById('proofPreview'),ph=document.getElementById('proofPlaceholder');if(!f){img.hidden=true;ph.hidden=false;return;}const r=new FileReader();r.onload=ev=>{img.src=ev.target.result;img.hidden=false;ph.hidden=true;};r.readAsDataURL(f);});
signBtn.addEventListener('click',()=>{validate();if(signBtn.disabled)return;const when=new Date();document.getElementById('signatureTime').textContent=when.toLocaleString();const record={order:order.value.trim(),customer:nameField.value.trim(),designVersion:version.value.trim(),amount:amount.value.trim(),signature:signature.value.trim(),signedAt:when.toISOString(),termsAccepted:true,designApproved:true};localStorage.setItem(`krs-approval-${record.order}`,JSON.stringify(record));status.className='form-status success';status.textContent='Design approved and Terms & Conditions accepted.';receipt.innerHTML=`<strong>${record.order}</strong><br>${record.customer}<br>${record.designVersion}<br>${record.amount}<br>Signed: ${when.toLocaleString()}`;paymentGate.hidden=false;signBtn.disabled=true;[order,nameField,version,amount,signature,...checks].forEach(el=>el.disabled=true);paymentGate.scrollIntoView({behavior:'smooth'});});
document.getElementById('payButton').addEventListener('click',()=>{if(approvalConfig.paymentUrl){window.location.href=approvalConfig.paymentUrl;}else{alert('Payment link has not been configured yet. Add the payment/invoice URL in approval.js.');}});
document.getElementById('year').textContent=new Date().getFullYear();
